name: api

services:

  db:
    image: postgres:17
    hostname: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volume/db:/var/lib/postgresql/data

  account:
    image: henriquebrnetto/account
    hostname: account
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    deploy:
      replicas: 1
    depends_on:
      - db

  auth:
    image: henriquebrnetto/auth
    hostname: auth
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - db

  gateway:
    image: henriquebrnetto/gateway
    ports:
      - 8080:8080
